export const PERMISSIONS = {
  VIEW_SUBSCRIPTIONS: "View Subscriptions",
  CREATE_SUBSCRIPTIONS: "Create Subscriptions",
  DELETE_SUBSCRIPTIONS: "Delete Subscriptions",
  UPDATE_SUBSCRIPTION: "Update Subscription",
  VIEW_MOVIES: "View Movies",
  CREATE_MOVIES: "Create Movies",
  DELETE_MOVIES: "Delete Movies",
  UPDATE_MOVIE: "Update Movie"
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];

export const PERMISSION_OPTIONS: Permission[] = [
  PERMISSIONS.VIEW_SUBSCRIPTIONS,
  PERMISSIONS.CREATE_SUBSCRIPTIONS,
  PERMISSIONS.DELETE_SUBSCRIPTIONS,
  PERMISSIONS.UPDATE_SUBSCRIPTION,
  PERMISSIONS.VIEW_MOVIES,
  PERMISSIONS.CREATE_MOVIES,
  PERMISSIONS.DELETE_MOVIES,
  PERMISSIONS.UPDATE_MOVIE,
];

export const SUBSCRIPTION_DEPENDENT_PERMISSIONS: Permission[] = [
  PERMISSIONS.CREATE_SUBSCRIPTIONS,
  PERMISSIONS.DELETE_SUBSCRIPTIONS,
  PERMISSIONS.UPDATE_SUBSCRIPTION,
];

export const MOVIE_DEPENDENT_PERMISSIONS: Permission[] = [
  PERMISSIONS.CREATE_MOVIES,
  PERMISSIONS.DELETE_MOVIES,
  PERMISSIONS.UPDATE_MOVIE,
];
